@startuml
skinparam shadowing false
skinparam activity {
  BackgroundColor #F8FAFC
  BorderColor #334155
  ArrowColor #0F172A
}

title Activity - Chọn ghế ngồi

start
:Truy cập bước Chọn ghế dựa vào suất chiếu;
:Hệ thống truy xuất sơ đồ phòng và phân loại ghế (trống / đã đặt / combo...);
:Lên màn hình giao diện sơ đồ ghế;
repeat
  :Người dùng click ghế ngồi;
  if (Ghế đã bán hoặc khóa?) then (Có)
    :Chặn chọn, báo ghế có người mua;
  else (Ghế trống)
    if (Ghế đó đang trong danh sách chọn của user?) then (Có)
      :Thực hiện hủy chọn ghế;
      :Loại khỏi giỏ tiền tạm;
    else (Chưa chọn)
      if (Check số ghế vượt quá qui định VD: max 8 ghế?) then (Có)
        :Báo lỗi tối đa lượng ghế cho phép;
      else (Không)
        :Thêm ghế vào giỏ;
        :Cập nhật giá tổng hóa đơn;
      endif
    endif
  endif
repeat while (Cần chọn thêm/đổi chỗ?) is (Có)

:Click tiếp tục;
:Chốt danh sách, chuyển bước Đồ ăn - Thanh toán;
stop
@enduml

